controller:
  replicaCount: 2
  podAnnotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "10254"
  metrics:
    enabled: "true"
  nodeSelector: 
   beta.kubernetes.io/os: linux
   agentpool: akswkpool
  defaultBackend:
    nodeSelector:
      beta.kubernetes.io/os: linux
  service:
    loadBalancerIP: <ILB_IP> #private IP
    annotations:
      service.beta.kubernetes.io/azure-load-balancer-internal: "true"

